# Generated by Django 5.2 on 2025-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('platina', 'Platina'), ('splendor', 'Splendor')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetrolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bikes', models.ManyToManyField(to='app.bike')),
            ],
        ),
    ]
